version: "3.9"

services:

  postgres:
    image: postgres:15.1
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password

volumes:
  postgres_volume:
