apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "base-frontend.fullname" . }}-fe-ingress-service
  labels:
  {{- include "base-frontend.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-rps: "200"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "base-frontend.fullname" . }}-todo-frontend-service'
            port:
              number: 80
        path: /
        pathType: Prefix