apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "base-frontend.fullname" . }}-frontend-access
  labels:
  {{- include "base-frontend.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  podSelector:
    matchLabels:
      component: todo-frontend