apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator-read-role
  namespace: todo-app
rules:
  - apiGroups: ["", "apps", "batch"]
    resources: ["nodes", "services", "pods", "pods/log", "deployments", "replicasets", "statefulsets", "jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator-write-role
  namespace: todo-app
rules:
  - apiGroups: ["", "apps", "batch"]
    resources: ["deployments", "replicasets", "statefulsets", "jobs", "cronjobs"]
    verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-read-role-binding
  namespace: todo-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-read-role
subjects:
- kind: User
  name: operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-write-role-binding
  namespace: todo-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-write-role
subjects:
- kind: User
  name: operator
  apiGroup: rbac.authorization.k8s.io