apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "base-redis.fullname" . }}-access
  labels:
  {{- include "base-redis.labels" . | nindent 4 }}
spec:
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
      podSelector:
        matchLabels:
          component: todo-api
  podSelector:
    matchLabels:
      component: redis
  policyTypes:
  - Egress
  - Ingress