apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "base-redis.fullname" . }}-deployment
  labels:
  {{- include "base-redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: redis
    {{- include "base-redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: redis
      {{- include "base-redis.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.deployment.redisClient.image.repository }}:{{ .Values.deployment.redisClient.image.tag | default .Chart.AppVersion }}
        name: redis-client
        ports:
        - containerPort: 6379
        resources: {{- toYaml .Values.deployment.redisClient.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false