kubernetesClusterDomain: cluster.local

# Values Api
deployment:
  apiContainer:
    image:
      repository: lucassctestregistry.azurecr.io/todo-api-image
      tag: v1
    resources:
      limits:
        cpu: 800m
        memory: 3000Mi
      requests:
        cpu: 650m
        memory: 2000Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 5008
    targetPort: 5008
  type: ClusterIP

#Values database
deployment:
  postgres:
    image:
      repository: postgres
      tag: "15.1"
  replicas: 1
kubernetesClusterDomain: cluster.local
pvc:
  qlDataClaim:
    storageClass: manual
    storageRequest: 10Gi
service:
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP

#Values frontend
deployment:
  frontendContainer:
    image:
      repository: lucassctestregistry.azurecr.io/todo-frontend-image
      tag: v1
    resources:
      limits:
        cpu: 100m
        memory: 250Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

#Values redis
deployment:
  redisClient:
    image:
      repository: redis
      tag: 7.0.7
    resources:
      limits:
        cpu: 250m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 256Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
