deployment:
  postgres:
    image:
      repository: postgres
      tag: "15.1"
  replicas: 1
kubernetesClusterDomain: cluster.local
pvc:
  qlDataClaim:
    storageClass: manual
    storageRequest: 10Gi
service:
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
