deployment:
  frontendContainer:
    image:
      repository: lucassctestregistry.azurecr.io/todo-frontend-image
      tag: v1
    resources:
      limits:
        cpu: 100m
        memory: 250Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
