kubernetesClusterDomain: cluster.local
todoFrontendDeployment:
  replicas: 1
  todoFrontendContainer:
    image:
      repository: lucassctestregistry.azurecr.io/todo-frontend-image
      tag: v1
    resources:
      limits:
        cpu: 100m
        memory: 250Mi
todoFrontendService:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
