apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "base-database.fullname" . }}-deployment
  labels:
  {{- include "base-database.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: postgres
    {{- include "base-database.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: postgres
      {{- include "base-database.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: software-containerization
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ include "base-database.fullname" . }}-postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ include "base-database.fullname" . }}-postgres
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.deployment.postgres.image.repository }}:{{ .Values.deployment.postgres.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: {{ include "base-database.fullname" . }}-ql-data-claim