apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "base-database.fullname" . }}-postgresql-data-claim
  labels:
  {{- include "base-database.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.postgresqlDataClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.postgresqlDataClaim.storageClass | quote }}