apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
  {{- include "base-database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: postgres
  {{- include "base-database.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}