apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: todo-app
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - port: 5008
      targetPort: 5008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: todo-app
spec:
  replicas: 1
  minReadySeconds: 30 # Wait 30 seconds before destroying old pods in case anything goes wrong
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: api-container
          image: lucassctestregistry.azurecr.io/todo-api-image:latest
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: "650m"
              memory: "2000Mi"
            limits:
              cpu: "800m"
              memory: "3000Mi"
          ports:
            - containerPort: 5008
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key
                  key: auth_key
            - name: REDIS_HOST
              value: redis-service
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: ENV
              value: test
      tolerations:
        - key: type
          operator: Equal
          value: application
          effect: NoSchedule
      nodeSelector:
        type: application