apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    component: todo-frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: todo-frontend
  template:
    metadata:
      labels:
        component: todo-frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: todo-frontend-container
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          resources:
            limits:
              memory: "250Mi"
              cpu: "100m"
          image: lucassctestregistry.azurecr.io/todo-frontend-image:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ENV
              value: test
      tolerations:
        - key: type
          operator: Equal
          value: application
          effect: NoSchedule
      nodeSelector:
        type: application