apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment
  labels:
    app: todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
      - name: todo-frontend-container
        image: lucassctestregistry.azurecr.io/todo-frontend-image:v1
        # imagePullPolicy: Always
        ports:
        - containerPort: 80