apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
  labels:
    component: redis
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis-client
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "250m"
          image: redis:7.0.7
          ports:
            - containerPort: 6379
