apiDeployment:
  apiContainer:
    image:
      repository: lucassctestregistry.azurecr.io/todo-api-image
      tag: v1
    resources:
      limits:
        cpu: 800m
        memory: 3000Mi
      requests:
        cpu: 650m
        memory: 2000Mi
  replicas: 1
apiService:
  ports:
  - port: 5008
    targetPort: 5008
  type: ClusterIP
jwtKey:
  authKey: cGluZGFrYWFz #pindakaas
kubernetesClusterDomain: cluster.local
postgres:
  password: RWdnc0JlbmVkaWN0MSE= # EggsBenedict1!
  username: cG9zdGdyZXM= # postgres
