apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
  {{- include "base-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.type }}
  selector:
    component: api
  {{- include "base-api.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.apiService.ports | toYaml | nindent 2 -}}