apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "base-api.fullname" . }}-api-access
  labels:
  {{- include "base-api.labels" . | nindent 4 }}
spec:
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - port: 5008
  podSelector:
    matchLabels:
      component: todo-api
  policyTypes:
  - Egress
  - Ingress