apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "base-api.fullname" . }}-api-deployment
  labels:
  {{- include "base-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiDeployment.replicas }}
  selector:
    matchLabels:
      component: api
    {{- include "base-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: api
      {{- include "base-api.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: auth_key
              name: {{ include "base-api.fullname" . }}-jwt-key
        - name: REDIS_HOST
          value: redis-service
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ include "base-api.fullname" . }}-postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ include "base-api.fullname" . }}-postgres
        - name: ENV
          value: test
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.apiDeployment.apiContainer.image.repository }}:{{ .Values.apiDeployment.apiContainer.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        name: api-container
        ports:
        - containerPort: 5008
        resources: {{- toYaml .Values.apiDeployment.apiContainer.resources | nindent 10
          }}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
      nodeSelector:
        type: application
      tolerations:
      - effect: NoSchedule
        key: type
        operator: Equal
        value: application