apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base-api.fullname" . }}-jwt-key
  labels:
  {{- include "base-api.labels" . | nindent 4 }}
data:
  auth_key: {{ required "jwtKey.authKey is required" .Values.jwtKey.authKey | b64enc
    | quote }}
type: Opaque