apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "base-database.fullname" . }}-ql-data
  labels:
    type: local
  {{- include "base-database.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/volume
  storageClassName: manual