deployment:
  redisClient:
    image:
      repository: redis
      tag: 7.0.7
    resources:
      limits:
        cpu: 250m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 256Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
